"""Add field to patient

Revision ID: 4ee550c7d49d
Revises: bd941f5c8ef2
Create Date: 2023-12-14 14:46:02.539921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee550c7d49d'
down_revision = 'bd941f5c8ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('person_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'person_details')
    # ### end Alembic commands ###
