"""Initial migration

Revision ID: ef16c462518c
Revises: 
Create Date: 2023-10-20 09:15:21.175513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef16c462518c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('home_address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient'))
    )
    # ### end Alembic commands ###
    patients_data_upgrade()


def patients_data_upgrade():
    """Add any optional data upgrade migrations here!"""
    table = sa.sql.table(
        'patient',
        sa.sql.column('name', sa.String),
        sa.sql.column('gender', sa.String),
        sa.sql.column('birth_date', sa.Date),
        sa.sql.column('home_address', sa.String)
    )
    op.bulk_insert(table,
        [
            {'name': 'John Doe', 'gender': 'Male', 'birth_date': '1990-01-01', 'home_address': '123 Main Street'},
            {'name': 'Jane Smith', 'gender': 'Female', 'birth_date': '1985-05-05', 'home_address': '456 Park Avenue'},
            {'name': 'Alice Johnson', 'gender': 'Female', 'birth_date': '1988-08-08', 'home_address': '789 Elm Road'},
            {'name': 'Bob Brown', 'gender': 'Male', 'birth_date': '1995-04-15', 'home_address': '567 Oak Lane'},
            {'name': 'Eva White', 'gender': 'Female', 'birth_date': '1980-12-10', 'home_address': '321 Pine Court'}
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
