services:  
  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/jenkins/workspace/poly+1:/gunicorn
     # network_mode: service:db 
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      net1:
        ipv4_address: 172.16.237.10
  db:
    image: mysql:8.1.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
     - MYSQL_DATABASE=mcaplpv1
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_ROOT_HOST=172.16.237.10
    networks:
      net1:
       ipv4_address: 172.16.237.11
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/jenkins/workspace/poly+1:/var/lib/mysql
      - /var/lib/jenkins/workspace/poly+:/docker-entrypoint-initdb.d/mcaplpv1.sql
volumes:
  db:
    driver: local
networks:
  net1:
    ipam:
      driver: default
      config:
        - subnet: 172.16.237.0/24